[package]
name = "int_ll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

memoffset = "0.9.0"

[dev-dependencies]

dyn_array = { git = "https://github.com/GumGun-rust/dyn_array" }
